export {
  acceptParentLinkHandler,
  admissionDecisionHandler,
  createAdmissionHandler,
  createEnrollmentHandler,
  getAdmissionHandler,
  getStudentHandler,
  getStudentProfileHandler,
  initiateParentLinkHandler,
  listAdmissionsHandler,
  listStudentsHandler,
  listTermEnrollmentRosterHandler,
  listLeavingCertificatesHandler,
  listStudentCertificatesHandler,
  generateLeavingCertificateHandler,
  recordIdentityAttestationHandler,
  setStudentPhotoHandler,
  transferStudentOutHandler,
} from './student.handler.js';
