export {
  acceptParentLinkHandler,
  admissionDecisionHandler,
  createAdmissionHandler,
  createEnrollmentHandler,
  getAdmissionHandler,
  getStudentHandler,
  getStudentProfileHandler,
  initiateParentLinkHandler,
  listAdmissionsHandler,
  listStudentsHandler,
  recordIdentityAttestationHandler,
  setStudentPhotoHandler,
  transferStudentOutHandler,
} from './student.handler.js';
