import type { StudentCertificateResponse } from '@loomis/contracts';
import { academicRepository } from '../../academic/repository/academic.repository.js';
import { storageService } from '../../storage/services/storage.service.js';
import { tenantRepository } from '../../tenant/repository/tenant.repository.js';
import { LoomisError } from '../../../shared/errors.js';
import { certificateRepository } from '../repository/certificate.repository.js';
import { studentRepository } from '../repository/student.repository.js';
import type { ActorContext } from '../types.js';
import { requireTenant } from './_shared.js';
import { buildCertificatePdf } from './certificate-pdf.js';

type PromotionRecordRow = {
  id: string;
  studentId: string;
  fromAcademicYearId: string;
  outcome: string;
};

function serializeCertificate(row: {
  id: string;
  tenantId: string;
  studentId: string;
  certificateType: string;
  certificateNumber: string;
  academicYearId: string | null;
  promotionRecordId: string | null;
  storageObjectId: string;
  issuedAt: Date;
  issuedById: string;
  createdAt: Date;
}): StudentCertificateResponse {
  return {
    id: row.id,
    tenantId: row.tenantId,
    studentId: row.studentId,
    certificateType: row.certificateType as StudentCertificateResponse['certificateType'],
    certificateNumber: row.certificateNumber,
    academicYearId: row.academicYearId,
    promotionRecordId: row.promotionRecordId,
    storageObjectId: row.storageObjectId,
    issuedAt: row.issuedAt.toISOString(),
    issuedById: row.issuedById,
    createdAt: row.createdAt.toISOString(),
  };
}

function buildCertificateNumber(admissionNo: string, yearLabel: string): string {
  const yearPart = yearLabel.replace(/\s+/g, '-').slice(0, 20);
  return `LC-${yearPart}-${admissionNo}`.slice(0, 64);
}

export const certificateService = {
  /**
   * Called after promotion confirmation — marks graduates and issues leaving certificates.
   */
  async processConfirmedGraduations(
    tenantId: string,
    confirmedRecords: PromotionRecordRow[],
    actor: ActorContext,
  ) {
    requireTenant(actor, tenantId);

    const graduated = confirmedRecords.filter((r) => r.outcome === 'graduated');
    for (const record of graduated) {
      await studentRepository.markGraduated(tenantId, record.studentId);
      await this.ensureLeavingCertificate(tenantId, record, actor);
    }
  },

  async ensureLeavingCertificate(
    tenantId: string,
    record: PromotionRecordRow,
    actor: ActorContext,
  ): Promise<StudentCertificateResponse> {
    requireTenant(actor, tenantId);

    const existing = await certificateRepository.findLeavingCertificate(
      tenantId,
      record.studentId,
      record.fromAcademicYearId,
    );
    if (existing) {
      return serializeCertificate(existing);
    }

    const student = await studentRepository.findStudentById(tenantId, record.studentId);
    if (!student) {
      throw new LoomisError('STUDENT_NOT_FOUND', 404, 'Student not found');
    }

    const year = await academicRepository.findYearById(tenantId, record.fromAcademicYearId);
    if (!year) {
      throw new LoomisError('ACADEMIC_YEAR_NOT_FOUND', 404, 'Academic year not found');
    }

    const tenant = await tenantRepository.findById(tenantId);
    const schoolName = tenant?.name ?? 'School';

    const certificateNumber = buildCertificateNumber(student.admissionNo, year.label);
    const issuedDate = new Date().toISOString().slice(0, 10);

    const pdf = buildCertificatePdf([
      schoolName.toUpperCase(),
      '',
      'CERTIFICATE OF COMPLETION',
      '',
      `This is to certify that ${student.firstName} ${student.lastName}`,
      `(Admission No: ${student.admissionNo})`,
      `has successfully completed the requirements of ${year.label}`,
      'and is hereby granted a Leaving Certificate.',
      '',
      `Certificate No: ${certificateNumber}`,
      `Date of Issue: ${issuedDate}`,
      '',
      'This document was generated by the Loomis platform.',
    ]);

    const { storageObjectId } = await storageService.storePlatformGeneratedObject({
      tenantId,
      ownerResourceType: 'student_certificate',
      ownerResourceId: record.studentId,
      classification: 'child_pii',
      contentType: 'application/pdf',
      body: pdf,
      createdByUserId: actor.userId,
    });

    const created = await certificateRepository.create(tenantId, {
      studentId: record.studentId,
      certificateType: 'leaving',
      certificateNumber,
      academicYearId: record.fromAcademicYearId,
      promotionRecordId: record.id,
      storageObjectId,
      issuedById: actor.userId,
    });

    return serializeCertificate(created);
  },

  async generateLeavingCertificateOnRequest(
    tenantId: string,
    studentId: string,
    academicYearId: string,
    actor: ActorContext,
  ): Promise<StudentCertificateResponse> {
    requireTenant(actor, tenantId);

    const promotionRecords = await academicRepository.listPromotions(tenantId, academicYearId);
    const record = promotionRecords.find(
      (r) =>
        r.studentId === studentId &&
        r.outcome === 'graduated' &&
        r.status === 'confirmed',
    );

    if (!record) {
      throw new LoomisError(
        'STUDENT_CERTIFICATE_NOT_ELIGIBLE',
        404,
        'No confirmed graduation record found for this student and year',
      );
    }

    return this.ensureLeavingCertificate(
      tenantId,
      {
        id: record.id,
        studentId: record.studentId,
        fromAcademicYearId: record.fromAcademicYearId,
        outcome: record.outcome,
      },
      actor,
    );
  },

  async listLeavingCertificatesForYear(tenantId: string, academicYearId: string, actor: ActorContext) {
    requireTenant(actor, tenantId);
    const rows = await certificateRepository.listLeavingCertificatesForYear(tenantId, academicYearId);
    return rows.map(serializeCertificate);
  },

  async listStudentCertificates(tenantId: string, studentId: string, actor: ActorContext) {
    requireTenant(actor, tenantId);
    const rows = await certificateRepository.listForStudent(tenantId, studentId);
    return rows.map(serializeCertificate);
  },
};
